### ISSUE TITLE
Delete island issue

### ISSUE THREAD

**Issue by Nedjii** [BentoBoxWorld/Border#10]
Hello, when I restart an island the previous one isn't deleted, I'm using paper 1.13.2 with bentobox 1.10.0 for 1.13.2,
regards.
edit : I figured  that the delete was working but really slow, anyway I get the error, would like to know why.
![image](https://user-images.githubusercontent.com/30918460/72313474-c1eb5180-368b-11ea-9d48-27317ebcee51.png)

**Comment by tastybento** [comment]
This was fixed in December, so the solution should be just to use the latest version. b4a8f08829ea86aa6d9b35cb692ba5a55664b6df
