### ISSUE TITLE
border in the nether

### ISSUE THREAD

**Issue by 100petr** [BentoBoxWorld/Border#100]
### Expected behavior

With this addon, you will be able to interact on the bskyblock nether

### Observed/Actual behavior

I updated the server from 1.19.2 to 1.19.3, updated bentobox + addons. But I found that with this addon you can't do any interactions on the bskyblock nether island - open chests, place/destroy blocks, etc. It looks like the border blocks these interactions, but the actual border that can't be crossed is correct.

### Steps/models to reproduce

Run bskyblock + border addon. It's fine on a normal island, but in the nether you can't interact while using this addon.

### BentoBox version

[08:44:53 INFO]: Běžím na PURPUR 1.19.3.
[08:44:53 INFO]: Verze BentoBox: 1.22.0
[08:44:53 INFO]: Databáze: JSON
[08:44:53 INFO]: Načtené herní světy:
[08:44:53 INFO]: bskyblock_world (BSkyBlock): Svět, Nether, End
[08:44:53 INFO]: Načtené doplňky:
[08:44:53 INFO]: Biomes 2.1.0 (ENABLED)
[08:44:53 INFO]: BSkyBlock 1.16.0 (ENABLED)
[08:44:53 INFO]: Challenges 1.1.0 (ENABLED)
[08:44:53 INFO]: ControlPanel 1.13.0 (ENABLED)
[08:44:53 INFO]: ItemsAdderHook 1.0.0-SNAPSHOT-b2 (ENABLED)
[08:44:53 INFO]: Level 2.9.0 (ENABLED)
I have the border addon removed now, but otherwise I had version 4.1.0

### Other

I also tried the latest build from jenkins.

**Comment by tastybento** [comment]
I can't replicate this. I an interact with my Nether island fine (open chests, break blocks etc.). 

Are you using the vanilla border or barrier blocks border?

What do you see if you type `/is info` when in the nether?

**Comment by tastybento** [comment]
Okay. Yes, a video will be useful.

**Comment by BONNe** [comment]
You could also try `/[admin_cmd] why <player>` command.
It should report if you were allowed or not to break blocks in the nether

**Comment by tastybento** [comment]
Weird. It's acting as if you are outside the border. 
If you do /is border I assume it turns off, and then does everything work?
I think where this is going is that I'm going to need a copy of your world (nether and overworld) and a copy of your Bentobox folder  so I can run it locally and see if I can replicate it.

**Comment by tastybento** [comment]
Got it. I'll test tonight.

**Comment by tastybento** [comment]
I just tried it, and everything works fine. :-( I go to 200,200 (your island?) and as Op I can work everything with or without the border operating. What version of the server are you using?

**Comment by tastybento** [comment]
Aha, I'm using paper. Where do you download that?

**Comment by BONNe** [comment]
> 1.19.3 purpur. try turning border off and on again (is border)

Can you please check that you have not set some custom world border for the nether world?
Could you check where exactly the border starts? If you go to 0,0 is it still outside the border?

**Comment by tastybento** [comment]
BTW, we don't use WorldBorderAPI anymore. You can remove that plugin.

I tried on a clean install of Paper build 499 and I can't replicate it. I suspect something similar to what BONNe is saying that there is something else setting the border. If you try a clean install, do you still see this?

**Comment by tastybento** [comment]
The border is being set for your own island, not the island you are on for some reason. That is why you appear to be outside your own island, because the border is around your own island.

**Comment by tastybento** [comment]
Okay, this is specific to the /is border command and unrelated to the Nether. To replicate:

1. Teleport to someone else's island
2. Issue the /is border command twice (once might be enough if it was off already)

**Comment by tastybento** [comment]
Try build 411 or later from https://ci.codemc.io/job/BentoBoxWorld/job/Border/
