### ISSUE TITLE
Add feature to disable spawn of blocks when player somehow get out of border

### ISSUE THREAD

**Issue by MorkaZ** [BentoBoxWorld/Border#118]
### Is your feature request related to a problem?

Yes. Players can grief someone's cave/island if they will tp out of cave/island and try to get back in by movement. They will get teleported back with spawn of stone block under them near border.

### Describe the solution you'd like.

Add feature in config which will allow to disable generation of this block. I know some players may fall or something but servers like mine allow players to fly and have keepinventory: true (gamerule) so in this case generating blocks like that make only troubles. 

### Describe alternatives you've considered.

Other alternative is to add option to teleport player to cave/island spawnpoint instead of nearest point of border with block under player. It would be also nice and solve this problem.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

Screenshot
![image](https://github.com/BentoBoxWorld/Border/assets/4214815/28cb9be1-550b-4708-8d48-506b3c893f9a)

**Comment by tastybento** [comment]
I added an option in config.yml to turn off the block.

**Comment by BONNe** [comment]
tasty, maybe better fix would be not to add the top-bottom block if player is in fly mode?
The issue why they are added are because players are flying

**Comment by tastybento** [comment]
Ah yes. That could be a good approach.

**Comment by tastybento** [comment]
Done.
