### ISSUE TITLE
Player's can't use /is border command

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Border#14]
#### Describe the bug
Players has bskyblock.border permission but not can use /is border command. Console saying "You have not permission."
Can you fix it?

**Comment by BONNe** [comment]
No

**Comment by OverBrave** [comment]
Ah, why

**Comment by tastybento** [comment]
Please do `bbox version` in the console and paste the result so I know what versions you are running, then I'll see if I can replicate.

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/73617032-b3111280-462b-11ea-9968-987e862d2ae6.png)

**Comment by BONNe** [comment]
Isn't it border.toggle ?

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/73617049-d63bc200-462b-11ea-87f0-98143d92d882.png)

**Comment by tastybento** [comment]
Permission should be `bskyblock.border.toggle`

**Comment by BONNe** [comment]
Or .*

**Comment by OverBrave** [comment]
Same. Nothing changed.

**Comment by BONNe** [comment]
You need development version

**Comment by OverBrave** [comment]
Already using dev build.

**Comment by OverBrave** [comment]
Okay, it's my problem. I am sorry for disturbing you. I'm writing wrong permission message.

**Comment by BONNe** [comment]
@tastybento  release numbers are messed up :(

**Comment by tastybento** [comment]
@BONNe I'm sorry, I don't understand. What's messed up?

**Comment by BONNe** [comment]
Build 9 till 13 is all 1.0.3 Release versions.
And it is not the same as in GitHub release page.

**Comment by tastybento** [comment]
Thanks. I did a proper release and switched the default branch.
