### ISSUE TITLE
Critical problem

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Border#2]
#### Describe the bug
When I return from the islands to the spawn, my screen turns red and does not allow us to do anything at the spawn. But if we're back in the spawn, the problem is solved. I understand there's a problem.
He doesn't allow us to do anything because we go out of the island boundaries when we go from the island to the spawn.

#### Screenshots and videos (Optional)
https://streamable.com/4zoxk

**Comment by tastybento** [comment]
Is the spawn in the same world as the islands, or another world?

**Comment by OverBrave** [comment]
Another.
![image](https://user-images.githubusercontent.com/47111280/71310774-f4a57f80-2428-11ea-8f36-12d6d428e1c3.png)

**Comment by tastybento** [comment]
Should be fixed now. Please test with the latest build.
