### ISSUE TITLE
Border doesn't work

### ISSUE THREAD

**Issue by frengor** [BentoBoxWorld/Border#21]
### Description
When someone changes world the border disables and never reappear to him.

#### Steps to reproduce the behavior
Do /is.
Create a nether portal.
Walk into it.
(or tp the player on PlayerJoinEvent to another world)

#### Expected behaviour
If you teleport the player on PlayerJoinEvent to another world, doing /is go won't show him the border. Also, if the PlayerJoinEvent has priority MONITOR, a red aura will be displayed to him.

#### Screenshots and videos
https://www.youtube.com/watch?v=ze0rVI8Z4Qw

### Environment
Java 8
Spigot 1.15.2

##### BentoBox Version (Mandatory)
Running SPIGOT 1.15.2.
BentoBox version: 1.11.1
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
Loaded Addons:
Biomes 1.6.0.1 (ENABLED)
Border 1.0.5 (ENABLED)
BSkyBlock 1.11.0 (ENABLED)
Chat 1.0.4 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
Level 1.9.3 (ENABLED)
Limits 1.9.2 (ENABLED)
TwerkingForTrees 1.1.2 (ENABLED)
Warps 1.9.0 (ENABLED)

#### Plugins (Optional)
FastAsyncWorldEdit, VoxelSniper, WorldBorderAPI, void-generator, Vault, WorldEdit, BentoBox

**Comment by tastybento** [comment]
Have a go with the build on the CI with this change in it.

**Comment by frengor** [comment]
It's working fine.
