### ISSUE TITLE
Bug border

### ISSUE THREAD

**Issue by Darkphenixs01** [BentoBoxWorld/Border#24]
662/5000
#### Describe the bug
If the player is in a world other than that of the islands and he tp on his island, the border does not appear.

#### Predictable behavior
The Border should appear

##### BentoBox version (required)
BentoBox version: 1.12.0
Biomes 1.6.0.1 (ENABLED)
Border 1.0.5 (ENABLED)
BSkyBlock 1.11.0 (ENABLED)
Challenges 0.8.0 (ENABLED)
Chat 1.0.4 (ENABLED)
Level 1.9.3 (ENABLED)
Likes 1.7.0 (ENABLED)
Limits 1.9.2 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
Warps 1.9.0 (ENABLED)

### Additional context (optional)

**Comment by tastybento** [comment]
Please upgrade to Border 1.0.6 that fixes this bug.
