### ISSUE TITLE
Border is near to my island

### ISSUE THREAD

**Issue by baalexan** [BentoBoxWorld/Border#26]
Hi,

I have got a problem after reboot, we can see on the screen my border don't protect my island. If I do /is i'm teleported in my island. 

https://i.imgur.com/Fer5cxm.png

BentoBox Version (Mandatory)
Running SPIGOT 1.15.2.
BentoBox version: 1.12.0
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.7.0. (ENABLED)
Border 1.0.7 (ENABLED)
BSkyBlock 1.12.0 (ENABLED)
Challenges 0.8.0 (ENABLED)
Chat 1.0.5 (ENABLED)
ControlPanel : 1.7.0 (ENABLED)
DimensionalTrees: 1.6.0 (ENABLED)
ExtraMobs : 1.11.0.2 (ENABLED)
IslandFly: 1.7.3 (ENABLED)
Level 1.9.3 (ENABLED)
Likes 1.7.1 (ENABLED)
Limits 1.9.4 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
Warps 1.9.3 (ENABLED)

**Comment by tastybento** [comment]
Did you change the island distance in config.yml? If so, change it back to what it was ASAP.

**Comment by tastybento** [comment]
If not, then when on your island do:

`/bsb info`

then do
`/bsb info (your name)`

Are they the same? Share screenshots.

**Comment by baalexan** [comment]
/bsb info : https://i.imgur.com/btSRlpL.png
/bsb info Zazira91 : https://i.imgur.com/PI2783d.png

I did not change the configuration, but I removed and put back magiccobblestonegenerator

**Comment by tastybento** [comment]
Okay, when you are on your island, what are your coordinates? Near x = 3200, z = 0? What are the coordinates of the border?
