### ISSUE TITLE
Escaping the border with a boat

### ISSUE THREAD

**Issue by iLemon** [BentoBoxWorld/Border#29]
Players can escape the island border by:

1) Place water that flows into the border
2) Place a boat, sit inside, move towards the border, leave the boat
3) You are now outside the border and can fly outside

**Comment by tastybento** [comment]
Try the latest snapshot and let me know if that works for you.

**Comment by Elioby** [comment]
Sorry for the delay, we (LemonCloud) confirmed this is fixed. Cheers!
