### ISSUE TITLE
Border error

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Border#31]
#### Screenshots and videos (Optional)
![image](https://user-images.githubusercontent.com/47111280/85952195-51519c00-b970-11ea-9d29-d214d0f7cf6e.png)
![image](https://user-images.githubusercontent.com/47111280/85952287-c4f3a900-b970-11ea-8531-c6bd297dde35.png)

##### Output of `/bbox version` (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/85952202-5b739a80-b970-11ea-8dd5-5f85bcc992c5.png)

WorldBorderPlugin-1.161.2 version

**Comment by tastybento** [comment]
Fixed with latest commit. Please try https://ci.codemc.io/job/BentoBoxWorld/job/Border/

**Comment by OverBrave** [comment]
Fixed, thanks!
