### ISSUE TITLE
Border 1.0.9 doesn't work with server 1.15.2.

### ISSUE THREAD

**Issue by iTaeyeonKim** [BentoBoxWorld/Border#33]
Border plugin 1.0.9 does not work with 1.14.0 bentobox

error log: https://pastebin.com/3W1wTrua

**Comment by tastybento** [comment]
@iTaeyeonKim Are you using the latest version of WorldBorderAPI plugin?

Also do `bbox version` and paste results here.

**Comment by iTaeyeonKim** [comment]
As I can see, I do:

http://i.pics.rs/FFFgX.png

http://i.pics.rs/RRRpZ.png

**Comment by iTaeyeonKim** [comment]
Oh, sorry , miss understood, I will try

**Comment by iTaeyeonKim** [comment]
Nope, still not working

**Comment by tastybento** [comment]
Do `bbox version` and paste results **of all of the output here.**

**Comment by iTaeyeonKim** [comment]
http://i.pics.rs/cccs6.png

here you go buddy

**Comment by iTaeyeonKim** [comment]
Sorry for bumping this thread, but how do I turn on new templates of magic cobblestone generator to be enabled by default, because now players must enable generators by them self.

And the only one generator I want to have for all island levels and all ranks is one default, so I don't need custom ones

https://pastebin.com/FWHSyTsu

How do I enable them by default, so players don't need manually to enable them to works, thanks

**Comment by tastybento** [comment]
It's best to ask those questions on the Discord server: https://discord.gg/sbPeyfw

I found the issue. The Border 1.0.9 is built against WorldBorderPlugin-1.161.2.jar, but that is only compatible with Minecraft 1.16.1. So, use [Border 1.0.7](https://github.com/BentoBoxWorld/Border/releases/tag/1.0.7) for now.

**Comment by tastybento** [comment]
Latest version should have not issues.
