### ISSUE TITLE
Change permission names and descriptions

### ISSUE THREAD

**Issue by fjeddy** [BentoBoxWorld/Border#40]
`[gamemode].border.off` is misgiving and confusing. The permission and it's associated descriptions make it sound like the border is actually turned off when used, not just made invisible.

Permission should be `[gamemode].border.visible` or `[gamemode].border.invisible`. But the permission .off should also exist, but in that case, literally turn off the border, not just make it invisible.

**Comment by tastybento** [comment]
That is an internal permission that is used by the addon and never should have to be given or removed manually or by any other process. It just tracks whether the border is on or off. Where did you see it, or where was it documented? The only public permission is the toggle permission.

With the latest version of Border, there is no continuously visible border. The modes are either the border blocks or it's not on at all.

**Comment by fjeddy** [comment]
Under releases..

`The default mode is that the border is on. The command is actually just adding or removing the [gamemode].border.off permission. So, if the player does not have the command permission, you can toggle the border using this permission instead.`

**Comment by tastybento** [comment]
Okay, noted. Anyway, `[gamemode].border.off` does turn off the border completely, including making it invisible, so the naming is accurate.
