### ISSUE TITLE
Player can throw item out of border

### ISSUE THREAD

**Issue by kit8379** [BentoBoxWorld/Border#53]
Exactly what the title means. Player can throw item out of border even the border is on (particle is visible). It is better to fix this and prevent player accidently throw out something to void which they can't take back.

**Comment by tastybento** [comment]
With Bskyblock I don't see a problem because the item will just drop into the void and disappear. Can you give more justification?

**Comment by kit8379** [comment]
That's the problem! Sometimes player will throw out something accidently and they can't take them back due to the border.

**Comment by tastybento** [comment]
But if you throw something into the void inside the border or outside then it falls into the void. The point of the border isn't to be a brick wall, it's just supposed to show you where the edge of the protection area is. Anyway, with the new version of Border you can turn off the barrier blocks and just have the particles to show you where the border is. Maybe that will be more to your liking.
