### ISSUE TITLE
Pistons

### ISSUE THREAD

**Issue by EvilLord1323** [BentoBoxWorld/Border#54]
Piston can push block out of border
![image](https://user-images.githubusercontent.com/57634139/104810319-60a91180-57fc-11eb-9ce6-4a4e95217552.png)

**Comment by Poslovitch** [comment]
Not a bug here.

I'll consider you're using BSkyblock. If you're not, then use the appropriate admin command:

1. `/bsbadmin settings`
2. Find the "Piston Push Protection" flag (icon: piston)
3. Make sure it is "Enabled".

And done!
