### ISSUE TITLE
Teleport back to island when out of border

### ISSUE THREAD

**Issue by Teric7** [BentoBoxWorld/Border#55]
#### Is your feature request related to a problem?

I do not want players to be able to phase through their island unless they do /spawn or /warp. Because when they have high ping they can lagg through the border

#### Describe the solution you'd like us to implement.

I would like you to make it an option to teleport players back into their island if they get out of it, unless they've used a command to do so. Or implement a physical border around a players island

#### Describe alternatives you've considered.

I've considered changing my server version and using Askyblock but due to feature I need I cannot do so.

**Comment by OverBrave** [comment]
Like VirtualBorder plugin.

**Comment by tastybento** [comment]
This is done in https://github.com/BentoBoxWorld/Border/releases/tag/2.1.0 .
