### ISSUE TITLE
An issue where the island doesnt spawn in the border, and the player dies when they respawn instantly

### ISSUE THREAD

**Issue by JusToastDEV** [BentoBoxWorld/Border#60]
#### Describe the bug
The title, and also the border is really long, and only has 2 visible walls

#### Steps to reproduce the behavior
player generates island, and teleports

#### Expected behavior
He will instantly die

#### Screenshots and videos (Optional)
https://ibb.co/r76zwFW

### Environment
void

##### Output of `/bbox version` (Mandatory)
Running: TUINITY 1.16.5
Bentobox version: 1.16.2
Database: JSON
Loaded Game Worlds:
bskyblock world (BSkyBlock): Overworld
Loaded Addons:
Border: 3.1.1 (ENABLED)
BSkyBlock: 1.14.4 (ENABLED)
Chat: 1.1.3 (ENABLED)
Visit: 1.3.0 (ENABLED)
```
_______
```

#### Plugins (Optional)
AdvancedHelp, ArmorStandTools, AuctionMaster, AuctionMasterItemDisplay, AutoPickup, BentoBox, BlockParticles, BowLotteries*, ChatGames, Citizens, CommandNPC*, CommandPanels, CommandToItem, CraftingStore, CrazyCrates, CubCustomDrops, CustomCrafting, CustomHeads*, CustomWhitelistMessage*, DiscordSRV, EpicRename, Essentials, EssentialsChat, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, goBrush, goPaint, HolographicDisplays, HolographicExtension, HolographicPlaceholders, ImageMaps, InteractiveChat, InteractiveChatDiscordSrvAddon, InvSeePlusPlus, ItemJoin, JoinCommands*, KnokkoCore, LuckPerms, MMOCore, MMOItems, MoneyPrinters, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, MyCommand, MythicLib, MythicMobs, OneStopShop, PlaceholderAPI, PlayerKits, PlayerParticles, Playtimes*, Prison, ProtocolLib, RealScoreboard, RevEnchants, SimpleCrops, TAB, TimeIsMoney*, Vault, ViaVersion, VoidGenerator, VoidSpawn, Votifier, VotingPlugin, WolfyUtilities, WorldBorder, WorldBorderAPI, WorldGuard
```
_______
```

**Comment by tastybento** [comment]
Does this happen with only player, or all players?

As Op or in Creative so you don't die, do `/is info` when inside the island space and share the output (screenshot). Also in the console do `is info (player name)` and share the output. Let's see what BentoBox thinks the island boundaries are.

**Comment by tastybento** [comment]
@JusToastDEV Can you answer above? ^^^
