### ISSUE TITLE
Visitors are not affected by the border.

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Border#62]
### Expected behavior

When visitors go to other islands, they can leave outside the borders of the islands. But the particles are still visible to them.

### Observed/Actual behavior

Başka adalara gittiklerinde, ada sınırından dışarı çıkamalılar.

### Steps/models to reproduce

Go to someone else's island and try going out of bounds.

### BentoBox version

![image](https://user-images.githubusercontent.com/47111280/129161453-a1430776-f505-4c13-91a0-d5c52f9bc98b.png)
![image](https://user-images.githubusercontent.com/47111280/129161486-52c8d4b4-f776-4047-b73a-763f661b4ae7.png)

**Comment by tastybento** [comment]
Hmm. I cannot replicate this right now. If a visitor goes to an island they see barrier blocks and are blocked. I assume you are using this config?

```
# Border Configuration file by tastybento
# 
# This list stores GameModes in which Border addon should not work.
# To disable addon it is necessary to write its name in new line that starts with -. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes: []
# 
# Use vanilla world border. Requires WorldBorderAPI plugin.
# Download from https://github.com/yannicklamprecht/WorldBorderAPI/releases
use-wbapi: false
# 
# Teleport players back inside the border if they somehow get outside.
# This will teleport players back inside if they toggle the border with a command.
return-teleport: true
# 
# Use barrier blocks. If false, the border is indicated by particles only.
# Only applicable if vanilla world border is not used
use-barrier-blocks: true
# 
# Default border behavior
show-by-default: true
# 
# Show max-protection range border. This is a visual border only and not a barrier.
show-max-border: true
```

**Comment by OverBrave** [comment]
I actually use the "use-barrier-block" setting off. I don't like it visually.Actually, another reason I didn't use it was to have players send messages when they are teleported back when they go out of bounds, but I guess there is no such setting.

And although I'm not sure, players who don't teleport, I think, close their island with "/is border off".

**Comment by tastybento** [comment]
I think I understand now. Border visibility is set by the player's setting, not the island's setting. So, if players can turn off border using `/is border off` then they will not see any border anywhere.

**Comment by OverBrave** [comment]
Actually, what I wanted was that even if the players closed the "border", they could not go to out the island borders. Because I perceived this command only as a particle concealer. If you see fit, it is ridiculous that the players are already out the island borders. Could you at least set something like this:
If players close the island borders with "/is border off", only the particle appearances will stop, but they will still not be able to go outside the island borders.

onlydisableparticles: true/false

**Comment by tastybento** [comment]
Okay, I added any option to the config to turn off particles. Check out the snapshot and let me know if it matches what you want.
cedf3c40c182be77aea0dd9076b0b441eccba53b
