### ISSUE TITLE
Border teleport problem

### ISSUE THREAD

**Issue by myavuzokumus** [BentoBoxWorld/Border#77]
### Expected behavior

Regardless, players must teleport once they are outside the boundaries of an island.

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/47111280/159174624-aacd600f-bd68-4b70-a8bf-87ba1ba258bc.png)
![image](https://user-images.githubusercontent.com/47111280/159174626-a6d502c1-62ba-4c62-9715-6fc3156563d2.png)

Visitors are not teleported in when they leave someone else's island.

They will teleport only if they move out of their island boundaries.

### Steps/models to reproduce

Try to leave someone else's island by boat.

### BentoBox version

![image](https://user-images.githubusercontent.com/47111280/159174869-7a4b973b-6beb-47fb-b3a6-50f9871c9af9.png)

**Comment by OverBrave** [comment]
But still creating stone near of island.

**Comment by OverBrave** [comment]
And barrier blocks and particles are broken. #85 
No longer appear. @tastybento

**Comment by tastybento** [comment]
Is this still an issue with the latest snapshot?

**Comment by OverBrave** [comment]
I don’t have the opportunity to try it. I will notify you if I am trying it in the future.
