### ISSUE TITLE
Border bug with normal nether and enderpearls

### ISSUE THREAD

**Issue by smashyalts** [BentoBoxWorld/Border#84]
### Expected behavior

Enderpearls working and useable to get to netherroof

### Observed/Actual behavior

border addon disables perms in nether around nether portal and in general disables enderpearls etc so nether roof is unreachable
enderpearls dissapears on throw

### Steps/models to reproduce

use a enderpearl with border addon on aoneblock in nether with normal nether

### BentoBox version

Running PURPUR 1.18.2.
BentoBox version: 1.20.1
Database: JSON
Loaded Game Worlds:
oneblock_world (OneBlock): Overworld, Nether*, The End
Loaded Addons:
AOneBlock 1.10.1 (ENABLED)
Bank 1.4.0 (ENABLED)
Border 4.0.0-SNAPSHOT-b140 (ENABLED)
Challenges 1.1.0-SNAPSHOT-b486 (ENABLED)
Level 2.9.0 (ENABLED)
TwerkingForTrees 1.4.3 (ENABLED)
Upgrades 0.3.0-SNAPSHOT-b94 (ENABLED)
Visit 1.4.0 (ENABLED)
Warps 1.12.0 (ENABLED)

**Comment by tastybento** [comment]
I can replicate on build 140, which you have, but not the latest snapshot. Try the latest and see if it works for you.
