### ISSUE TITLE
Barrier blocks are gone

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Border#85]
### Expected behavior

Barrier block need to block to player

### Observed/Actual behavior

After upgrade Bentobox version to latest snapshot version (1.21.0 b2267). Barrier blocks and particles are gone and when player trying to go outside of island, just back teleport to the island and is seems is a bug. It need to appear barrier block. Also particles not appear.

Maybe it also can because of latest develop version of border addon.

### Steps/models to reproduce

Just upgrade the Bentobox version to latest snapshot with latest border addon version.

### BentoBox version

![image](https://user-images.githubusercontent.com/47111280/174658117-deae03ad-ac4f-4bf7-a7c5-5592e375cf31.png)

**Comment by BONNe** [comment]
I will keep this open until BentoBox 1.21 release.

After that Border requires changes that should reenable Barrier block showing.

**Comment by tastybento** [comment]
Works now (I hope!)
