### ISSUE TITLE
Last dev build error

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Border#9]
> [12:34:30] [Craft Scheduler Thread - 111/ERROR]: [BentoBox] Could not load file 'database/BorderData/19475d29-3696-3c29-ab37-62427e970da0.json': File not found.
[12:34:30] [Craft Scheduler Thread - 113/ERROR]: [BentoBox] Could not load file 'database/BorderData/d583855e-2916-3fad-8c6f-0cbe3bd46807.json': File not found.
[12:34:30] [Craft Scheduler Thread - 53/ERROR]: [BentoBox] Could not load file 'database/BorderData/d583855e-2916-3fad-8c6f-0cbe3bd46807.json': File not found.
[12:34:30] [Craft Scheduler Thread - 107/ERROR]: [BentoBox] Could not load file 'database/BorderData/19475d29-3696-3c29-ab37-62427e970da0.json': File not found.`

> Second error moved the another issiue

**Comment by Poslovitch** [comment]
The second error comes from the Level addon, please update it to a newer build.

**Comment by OverBrave** [comment]
> The second error comes from the Level addon, please update it to a newer build.

Already updated
![image](https://user-images.githubusercontent.com/47111280/72202430-80cb2580-3470-11ea-99d4-ff2495635698.png)

**Comment by OverBrave** [comment]
At the same time, when the borders are closed, players can go out of the island. It must remain an invisible wall.

**Comment by OverBrave** [comment]
And every time you enter the server, the screen is red again. And we can't do anything.

**Comment by OverBrave** [comment]
Virtual Border : https://github.com/Eole7/VirtualBorder

**Comment by tastybento** [comment]
I'm sorry, I'm lost. What's the problem right now?

**Comment by OverBrave** [comment]
> I'm sorry, I'm lost. What's the problem right now?
https://github.com/BentoBoxWorld/BentoBox/issues/1143

**Comment by mrfloris** [comment]
Sorry that you don't understand what we think the problem is. 
Linking mine to this one and then this one to mine doesn't help resolve the matter either.
