### ISSUE TITLE
Make it so your border settings are global and not per player.

### ISSUE THREAD

**Issue by OneblockNation** [BentoBoxWorld/Border#97]
### Is your feature request related to a problem?

Yes. We use a cosmetics plugin that allows players to ride an enderdragon, for example.

Player's can Ride right through the border. Even though we disabled the vanilla border, those who had an island before the change will not get the barrier border to prevent this issue.

### Describe the solution you'd like.

Make it so the settings in border.yml are used globablly and will update all existing and future islands to the specified border type.

### Describe alternatives you've considered.

Adjusting the settings multiple times, nothing fixes it.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
I think this should work. I have not had a chance to do a lot of testing on it yet.

**Comment by OneblockNation** [comment]
> I think this should work. I have not had a chance to do a lot of testing on it yet.

Sadly, it doesn't!

Unfortunately, I was told by BONNe1704 that I would need to let players have access to switching border types so that they HAVE to change it to the barriered. Despite me choosing Barrier and DISABLING vanilla border. I was also told by setting barrier to default, players who joined AFTER, and not before, would only see the new world border type. However, I tested this and it doesnt seem to work.

**Comment by tastybento** [comment]
I haven't finished this yet. I will be able to debug over the weekend. I've rewritten how things work so that if a player does not have permission to use the commands then their setting will be set to what is in the config.yml. So, to test this players must not have the perms. 
Like I said though I haven't had a chance to test this yet - too much IRL work. So please wait a while.

**Comment by tastybento** [comment]
Okay, this is done now. Essentially, if a player does not have permission to toggle the border or change the border types then they will be reset to the default value in config.yml the next time they login.

**Comment by tastybento** [comment]
Latest snapshot with this in https://ci.codemc.io/job/BentoBoxWorld/job/Border/. Note that the layout of config.yml has changed too, so check that out.
